import '../../data/models/recipe_model.dart';
import '../entities/category_entity.dart';
import '../entities/recipe_entity.dart';

abstract class RecipeRepository {
  Future<List<CategoryEntity>> getCategories();
  Future<void> addRecipe(RecipeEntity recipe);
  static final List<Recipe> allRecipes = [

// ==========================================
    // 1. BREAKFAST (الفطور الشرقي والغربي)
    // ==========================================
    Recipe(
      id: 1,
      title: 'Shakshuka 🍳',
      category: 'Breakfast',
      ingredients: '4 Eggs, 3 Tomatoes, 1 Onion, 2 Garlic cloves, 1 Bell pepper, 2 tbsp Olive oil, Cumin, Salt, Black pepper',
      instructions: '1. Sauté chopped onion, garlic, and pepper in olive oil until soft. 2. Add chopped tomatoes and spices, simmer for 10 mins. 3. Crack eggs on top, cover and cook for 5 mins until eggs are set.',
      calories: 320,
      time: 15,
      imagePath: 'assets/images/shakshuka.png',
      isFavorite: false,
    ),
    Recipe(
      id: 2,
      title: 'Fava Beans (Foul) 🧆',
      category: 'Breakfast',
      ingredients: '1 can Fava beans, 3 tbsp Olive oil, 1 Lemon (juiced), 1 clove Garlic (minced), 1/2 tsp Cumin, Fresh parsley, Chopped tomatoes',
      instructions: '1. Heat the beans in a pot and mash them slightly. 2. Add garlic, lemon juice, and cumin; mix well. 3. Pour into a serving dish, top with olive oil, parsley, and tomatoes.',
      calories: 280,
      time: 10,
      imagePath: 'assets/images/foul.png',
      isFavorite: false,
    ),
    Recipe(
      id: 3,
      title: 'Hummus with Tahini 🥣',
      category: 'Breakfast',
      ingredients: '2 cups Cooked chickpeas, 1/2 cup Tahini, 1/4 cup Lemon juice, 1 Garlic clove, Salt, Ice water, Olive oil, Paprika',
      instructions: '1. Blend chickpeas, garlic, and salt in a food processor. 2. Gradually add tahini and lemon juice, then ice water until smooth. 3. Serve in a bowl with a well of olive oil and a sprinkle of paprika.',
      calories: 350,
      time: 15,
      imagePath: 'assets/images/hummus.png',
      isFavorite: false,
    ),
    Recipe(
      id: 4,
      title: 'Labneh with Zaatar 🥛',
      category: 'Breakfast',
      ingredients: '1 cup Labneh, 2 tbsp Zaatar, 3 tbsp Extra virgin olive oil, Fresh mint, Black olives, Sliced cucumbers',
      instructions: '1. Spread the labneh on a small plate using a spoon to create a swirl. 2. Sprinkle zaatar in the center and drizzle generously with olive oil. 3. Garnish with mint, olives, and serve with bread.',
      calories: 210,
      time: 5,
      imagePath: 'assets/images/labneh.png',
      isFavorite: false,
    ),
    Recipe(
      id: 5,
      title: 'Falafel with Arabic Bread 🥙',
      category: 'Breakfast',
      ingredients: '6-8 Falafel pieces, 2 Arabic breads, Tahini sauce, Chopped pickles, Tomatoes, Mint leaves',
      instructions: '1. Reheat falafel if needed. 2. Open the bread and spread a layer of tahini. 3. Stuff with crushed falafel, tomatoes, pickles, and mint.',
      calories: 450,
      time: 10,
      imagePath: 'assets/images/falafel.png',
      isFavorite: false,
    ),
    Recipe(
      id: 6,
      title: 'Hummus Fatteh 🥣',
      category: 'Breakfast',
      ingredients: '2 cups Toasted bread cubes, 2 cups Warm chickpeas, 1 cup Yogurt, 2 tbsp Tahini, 1 Garlic clove, Roasted pine nuts, Butter',
      instructions: '1. Place toasted bread in a dish and soak with a little chickpea broth. 2. Layer chickpeas over bread. 3. Mix yogurt, tahini, and garlic, pour over top. Garnish with nuts fried in butter.',
      calories: 520,
      time: 20,
      imagePath: 'assets/images/fatteh.png',
      isFavorite: false,
    ),
    Recipe(
      id: 11,
      title: 'Honey Pancakes 🥞',
      category: 'Breakfast',
      ingredients: '1 cup Flour, 1 cup Milk, 1 Egg, 2 tbsp Sugar, 1 tsp Baking powder, Butter, Honey, Berries',
      instructions: '1. Whisk flour, sugar, and baking powder. Add egg and milk; mix until smooth. 2. Cook small ladles of batter on a buttered pan until bubbles form, then flip. 3. Stack and serve with honey and fruit.',
      calories: 380,
      time: 20,
      imagePath: 'assets/images/pancakes.png',
      isFavorite: false,
    ),
    Recipe(
      id: 12,
      title: 'French Toast 🍞',
      category: 'Breakfast',
      ingredients: '2 slices Thick bread, 2 Eggs, 1/4 cup Milk, 1/2 tsp Cinnamon, 1/2 tsp Vanilla, Butter, Maple syrup',
      instructions: '1. Whisk eggs, milk, cinnamon, and vanilla in a shallow bowl. 2. Dip bread slices into the mixture until soaked. 3. Fry in a buttered pan until golden on both sides. Serve with syrup.',
      calories: 410,
      time: 12,
      imagePath: 'assets/images/french_toast.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 13,
      title: 'Avocado Toast with Egg 🥑',
      category: 'Breakfast',
      ingredients: '1 slice Sourdough bread, 1/2 ripe Avocado, 1 Fried or Poached egg, Lemon juice, Chili flakes, Salt',
      instructions: '1. Toast the bread. Mash avocado with lemon and salt, then spread on toast. 2. Top with the egg. 3. Sprinkle with chili flakes and serve immediately.',
      calories: 340,
      time: 10,
      imagePath: 'assets/images/avocado_egg.png',
      isFavorite: false,
    ),
    Recipe(
      id: 14,
      title: 'Cheese & Veggie Omelette 🍳',
      category: 'Breakfast',
      ingredients: '3 Eggs, 1/4 cup Cheddar cheese, 2 tbsp Chopped bell peppers, 1 tbsp Onions, Salt, Pepper, Butter',
      instructions: '1. Whisk eggs with salt and pepper. 2. Sauté peppers and onions in butter, then pour in eggs. 3. When set, sprinkle cheese on one side, fold over, and cook until melted.',
      calories: 310,
      time: 8,
      imagePath: 'assets/images/omelette.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 15,
      title: 'Waffles with Fruits 🧇',
      category: 'Breakfast',
      ingredients: '2 Waffles, 1/2 cup Whipped cream, Sliced strawberries, Blueberries, Maple syrup',
      instructions: '1. Toast waffles until crispy. 2. Top with a dollop of whipped cream and fresh fruits. 3. Drizzle with maple syrup and serve.',
      calories: 420,
      time: 15,
      imagePath: 'assets/images/waffles.jpg',
      isFavorite: false,
    ),
    // 2. LUNCH (الغداء)
    Recipe(
      id: 10,
      title: 'Jordanian Mansaf 🍖',
      category: 'Lunch',
      ingredients: 'Lamb, Jameed, Rice, Shrak bread, Almonds',
      instructions: 'Cook meat in jameed sauce, serve over rice and bread.',
      calories: 950,
      time: 120,
      imagePath: 'assets/images/mansaf.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 11,
      title: 'Chicken Maqluba 🍲',
      category: 'Lunch',
      ingredients: 'Chicken, Rice, Cauliflower, Eggplant, Spices',
      instructions: 'Layer vegetables and chicken with rice, flip after cooking.',
      calories: 620,
      time: 60,
      imagePath: 'assets/images/maqluba.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 12,
      title: 'Stuffed Vine Leaves 🍇',
      category: 'Lunch',
      ingredients: 'Vine leaves, Rice, Minced meat, Lemon',
      instructions: 'Stuff leaves with rice mix and slow cook with lemon.',
      calories: 480,
      time: 150,
      imagePath: 'assets/images/vine_leaves.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 13,
      title: 'Chicken Kabsa 🇸🇦',
      category: 'Lunch',
      ingredients: 'Long grain rice, Chicken, Kabsa spices, Tomatoes, Almonds',
      instructions: 'Cook chicken with spices, then cook rice in the same broth.',
      calories: 580,
      time: 50,
      imagePath: 'assets/images/kabsa.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 14,
      title: 'Chicken Musakhan 🇵🇸',
      category: 'Lunch',
      ingredients: 'Taboon bread, Chicken, Onions, Sumac, Olive oil',
      instructions: 'Caramelize onions with sumac, roast chicken, and serve over bread.',
      calories: 750,
      time: 65,
      imagePath: 'assets/images/musakhan.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 15,
      title: 'Pasta Bolognese 🍝',
      category: 'Lunch',
      ingredients: 'Spaghetti, Minced beef, Tomato sauce, Parmesan',
      instructions: 'Cook beef with sauce, serve over boiled pasta.',
      calories: 520,
      time: 40,
      imagePath: 'assets/images/bolognese.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 16,
      title: 'Classic Lasagna 🥘',
      category: 'Lunch',
      ingredients: 'Lasagna sheets, meat sauce, Béchamel, Mozzarella',
      instructions: 'Layer pasta with meat and bechamel, then bake.',
      calories: 680,
      time: 60,
      imagePath: 'assets/images/lasagna.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 17,
      title: 'Chicken Alfredo ⚪',
      category: 'Lunch',
      ingredients: 'Fettuccine, Chicken, Heavy cream, Garlic, Parmesan',
      instructions: 'Sauté chicken, prepare cream sauce, and toss with pasta.',
      calories: 750,
      time: 25,
      imagePath: 'assets/images/chicken_alfredo.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 18,
      title: 'Steak with Potatoes 🥩',
      category: 'Lunch',
      ingredients: 'Beef steak, Potatoes, Rosemary, Butter, Garlic',
      instructions: 'Sear steak, serve with roasted or mashed garlic potatoes.',
      calories: 620,
      time: 30,
      imagePath: 'assets/images/steak_potatoes.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 19,
      title: 'Classic Beef Burger 🍔',
      category: 'Lunch',
      ingredients: 'Beef patty, Brioche bun, Cheese, Lettuce, Special sauce',
      instructions: 'Grill patty, melt cheese, and assemble in bun.',
      calories: 710,
      time: 20,
      imagePath: 'assets/images/beef_burger.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 20,
      title: 'Creamy Fettuccine 🍄',
      category: 'Lunch',
      ingredients: 'Fettuccine, Mushrooms, Heavy cream, Garlic, Parmesan',
      instructions: 'Cook mushrooms in garlic butter, add cream and toss with pasta.',
      calories: 720,
      time: 20,
      imagePath: 'assets/images/fettuccine_cream.jpg',
      isFavorite: false,
    ),
    // 3. DINNER (العشاء) -
    Recipe(
      id: 34,
      title: 'Vegetable Noodles 🍜',
      category: 'Dinner',
      ingredients: 'Egg noodles, Soy sauce, Cabbage, Carrots, Sesame oil',
      instructions: 'Stir-fry vegetables, add noodles and soy sauce.',
      calories: 380,
      time: 15,
      imagePath: 'assets/images/veg_noodles.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 35,
      title: 'Chicken Stir-Fry 🥢',
      category: 'Dinner',
      ingredients: 'Chicken, Broccoli, Ginger, Garlic, Soy sauce',
      instructions: 'Sauté chicken and veggies with ginger-soy glaze.',
      calories: 420,
      time: 20,
      imagePath: 'assets/images/chicken_stirfry.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 36,
      title: 'Assorted Sushi Roll 🍣',
      category: 'Dinner',
      ingredients: 'Sushi rice, Nori, Salmon/Tuna, Avocado',
      instructions: 'Spread rice on nori, add fillings, roll and slice.',
      calories: 320,
      time: 45,
      imagePath: 'assets/images/sushi.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 37,
      title: 'Japanese Ramen 🥣',
      category: 'Dinner',
      ingredients: 'Ramen noodles, Savory broth, Boiled egg, Seaweed',
      instructions: 'Prepare broth, add noodles and top with egg.',
      calories: 550,
      time: 30,
      imagePath: 'assets/images/ramen.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 38,
      title: 'Margherita Pizza 🍕',
      category: 'Dinner',
      ingredients: 'Pizza dough, Tomato sauce, Mozzarella, Basil',
      instructions: 'Spread sauce and cheese, bake until golden.',
      calories: 300,
      time: 40,
      imagePath: 'assets/images/margherita_pizza.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 39,
      title: 'Chicken Quesadilla 🌮',
      category: 'Dinner',
      ingredients: 'Tortilla, Shredded chicken, Cheddar, Peppers',
      instructions: 'Grill chicken and cheese in tortillas until melted.',
      calories: 480,
      time: 15,
      imagePath: 'assets/images/quesadilla.jpg',
      isFavorite: false,
    ),

    // ==========================================
    // 4. SALADS (السلطات) - IDs: 51 to 58
    // ==========================================
    Recipe(
      id: 51,
      title: 'Fattoush Salad 🥗',
      category: 'Salads',
      ingredients: 'Cucumber, Tomatoes, Toasted bread, Sumac',
      instructions: 'Chop veggies, mix with dressing and fried bread.',
      calories: 160,
      time: 15,
      imagePath: 'assets/images/fattoush.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 52,
      title: 'Authentic Tabbouleh 🌿',
      category: 'Salads',
      ingredients: 'Parsley, Mint, Tomatoes, Bulgur, Lemon',
      instructions: 'Finely chop herbs, mix with bulgur and lemon dressing.',
      calories: 180,
      time: 25,
      imagePath: 'assets/images/tabbouleh.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 53,
      title: 'Greek Salad 🧀',
      category: 'Salads',
      ingredients: 'Cucumber, Tomatoes, Olives, Feta cheese',
      instructions: 'Combine veggies and olives, top with feta and oregano.',
      calories: 210,
      time: 10,
      imagePath: 'assets/images/greek_salad.jpg',
      isFavorite: false,
    ),

    // ==========================================
    // 5. APPETIZERS (المقبلات) - IDs: 59 to 66
    // ==========================================
    Recipe(
      id: 59,
      title: 'Creamy Hummus 🥣',
      category: 'Appetizers',
      ingredients: 'Chickpeas, Tahini, Garlic, Lemon, Olive oil',
      instructions: 'Blend ingredients until smooth, drizzle with olive oil.',
      calories: 250,
      time: 15,
      imagePath: 'assets/images/hummus.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 60,
      title: 'Crispy Sambousek 🥟',
      category: 'Appetizers',
      ingredients: 'Pastry dough, Meat or Cheese, Onions',
      instructions: 'Fill dough, fold into triangles, and deep fry.',
      calories: 120,
      time: 30,
      imagePath: 'assets/images/sambousek.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 61,
      title: 'Fried Kibbeh 🥟',
      category: 'Appetizers',
      ingredients: 'Bulgur, Minced meat, Onions, Pine nuts',
      instructions: 'Stuff bulgur shell with meat and fry until golden.',
      calories: 150,
      time: 50,
      imagePath: 'assets/images/kibbeh.jpg',
      isFavorite: false,
    ),

    // ==========================================
    // 6. DESSERTS (الحلويات) - IDs: 67 to 76
    // ==========================================
    Recipe(
      id: 67,
      title: 'Cheese Kunafa 🧀',
      category: 'Desserts',
      ingredients: 'Phyllo dough, Nabulsi cheese, Sugar syrup',
      instructions: 'Layer dough and cheese, bake and soak with syrup.',
      calories: 450,
      time: 40,
      imagePath: 'assets/images/kunafa.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 68,
      title: 'Chocolate Brownies 🍫',
      category: 'Desserts',
      ingredients: 'Dark chocolate, Cocoa, Flour, Eggs, Butter',
      instructions: 'Melt chocolate and butter, mix with eggs and bake.',
      calories: 290,
      time: 35,
      imagePath: 'assets/images/brownies.jpg',
      isFavorite: false,
    ),

    // ==========================================
    // 7. DRINKS (المشروبات) - IDs: 77 to 91
    // ==========================================
    Recipe(
      id: 77,
      title: 'Mint Lemonade 🍋',
      category: 'Drinks',
      ingredients: 'Fresh lemons, Mint, Sugar, Cold water',
      instructions: 'Blend ingredients, strain and serve over ice.',
      calories: 120,
      time: 5,
      imagePath: 'assets/images/mint_lemonade.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 85,
      title: 'Arabic Coffee ☕',
      category: 'Drinks',
      ingredients: 'Coffee beans, Cardamom, Saffron, Water',
      instructions: 'Boil coffee and cardamom for 15 minutes.',
      calories: 5,
      time: 20,
      imagePath: 'assets/images/arabic_coffee.jpg',
      isFavorite: false,
    ),

    // ==========================================
    // 8. HEALTHY (الأكل الصحي) - IDs: 92 to 99
    // ==========================================
    Recipe(
      id: 92,
      title: 'Grilled Chicken Salad 🥗',
      category: 'Healthy',
      ingredients: 'Chicken breast, Mixed greens, Lemon-oil dressing',
      instructions: 'Serve grilled chicken over fresh greens.',
      calories: 310,
      time: 20,
      imagePath: 'assets/images/grilled_chicken_salad.jpg',
      isFavorite: false,
    ),
    Recipe(
      id: 94,
      title: 'Salmon with Roasted Veggies 🐟',
      category: 'Healthy',
      ingredients: 'Salmon, Asparagus, Carrots, Lemon, Garlic',
      instructions: 'Season salmon and veggies and bake in oven.',
      calories: 420,
      time: 25,
      imagePath: 'assets/images/salmon_veggies.jpg',
      isFavorite: false,
    ),
  ];

  static List<Recipe> getFavoriteRecipes() {
    return allRecipes.where((r) => r.isFavorite).toList();
  }
}